### PR TITLE
fix(input toggle): fix styling bug

### PR DESCRIPTION
**Pull request by bethbertozzi**
## Summary

**Input Toggle**

bug on hover when used within cellComponent and presumably other components. I changed the hove color from white to transparent. As well, there is a 10px margin-bottom on input toggle, meant for when it is beside another component. I am waiting to hear if this should be kept or removed

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

### CODE REVIEW

**Review by masoudmanson — APPROVED** [review]
LGTM @bethbertozzi 
Thank you 💯

**Review by clarsen-czi — DISMISSED** [review]
Looks like the InputToggle wasn't placed into the component cell, but everything else looks good!

**Comment by bethbertozzi** [comment]
@clarsen-czi that will be fixed in this pr: https://github.com/chanzuckerberg/sci-components/pull/255

**Review by clarsen-czi — APPROVED** [review]
LGTM! Thanks @bethbertozzi !

**Pull request merged**
