### PR TITLE
fix(accordion): defaultExpanded now works as expected

### PR DESCRIPTION
**Pull request by masoudmanson**
## Summary

**Accordion**
Github issue: #625 

The SDS Accordion component is built off the MUI Accordion component, which has a prop of defaultExpanded. When true / present, this boolean prop forces the Accordion to be open by default (users can still close it). However, this does not work with SDS Accordion if this prop is manually added; it has no effect.

The Accordion with the defaultExpanded prop should have been expanded!

### CODE REVIEW

**Review by tihuan — APPROVED** [review]
Oh perfect!! Thanks for adding support for this prop, @masoudmanson 😄 🙏 LGTM!!

**Review by clarsen-czi — CHANGES_REQUESTED** [review]
@masoudmanson looks like this isn't working in Storybook via Chromatic. Not sure if there's actually an issue or if Chromatic is just being fussy. Take a look and LMK. Thanks!

**Comment by masoudmanson** [comment]
@clarsen-czi, could you please check this link:
https://616981d9028812003ade73f3-pciozcnerq.chromatic.com/?path=/story/components-accordion--default&args=defaultExpanded:!true

After enabling the defaultExpanded prop, you'll need to refresh the page to see the Accordion expanded by default. The link above already has the prop set, so you should see the Accordion in its expanded state. Let me know if it's still not working!

**Comment by clarsen-czi** [comment]
> @clarsen-czi, could you please check this link: https://616981d9028812003ade73f3-pciozcnerq.chromatic.com/?path=/story/components-accordion--default&args=defaultExpanded:!true
> 
> After enabling the defaultExpanded prop, you'll need to refresh the page to see the Accordion expanded by default. The link above already has the prop set, so you should see the Accordion in its expanded state. Let me know if it's still not working!

Looks like it's working! Thanks for providing the link to check @masoudmanson

**Review by clarsen-czi — APPROVED** [review]
Looks like it's working!! Thanks @masoudmanson

**Pull request merged**
