### PR TITLE
test(TagFilter): TagFilter screenshot test

### PR DESCRIPTION
**Pull request by liaprins**
## Summary

**TagFilter**
Github issue: #492 
### Permutation dimensions to include
- [x] **pseudo-state:** default, hover, active, focus

#### Exceptions, notes
- This should be a pretty basic test that only needs to iterate through the pseudo-states.

_Here's a screenshot of the (very basic) story UI_
Screenshot 2023-06-02 at 11 13 06 AM

## Checklist

- [x] Default Story in Storybook
- [x] LivePreview Story in Storybook
- [x] Test Story in Storybook
- [x] Tests written
- [x] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary // liaprins: N/A
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

### CODE REVIEW

**Comment by liaprins** [comment]
> Looks like the DropdownMenu components are overlapping in the screenshot. Maybe we just need more spaces among the dropdowns?
> 
> Thank you!
> 
> Screenshot 2023-06-06 at 9 22 32 AM

I think this was supposed to be left as a comment in the DropdownMenu PR, so [I copied it as its own comment over there](https://github.com/chanzuckerberg/sci-components/pull/490#issuecomment-1579199012), @tihuan , just FYI! and will make the fix soon!

**Comment by liaprins** [comment]
@tihuan Does anything need to change for this TagFilter PR before it could be approved or merged?

**Comment by tihuan** [comment]
Ah no, I think this PR is good to merge 👌 Thanks, Lia!

**Comment by liaprins** [comment]
> Ah no, I think this PR is good to merge 👌 Thanks, Lia!

Okay thanks! I think you need to approve it or else I can't merge it in without that though, right? Thanks for your help!

**Review by tihuan — APPROVED** [review]

**Comment by tihuan** [comment]
That's right lol Sorry thought I approved already ahaha done!

**Pull request merged**
