### PR TITLE
chore(storybook): upgrade storybook

### PR DESCRIPTION
**Pull request by tihuan**
Upgrade storybook! PTAL thank you 😄 🙏

### CODE REVIEW

**Review by mdjmoore — APPROVED** [review]
( ◑ ᗜ ◑ )

**Comment by jfoo1984** [comment]
late comment on this, but do we want to consider pinning the version to a specific version and not allow patch version updates with `^`?  My reasoning on this is that this will insure consistency in whatever environment someone is installing the repo, and forces us to be more intentional about updating our package versions.

**Comment by tihuan** [comment]
Hey @jfoo1984 ! Ooh that's a good question 💡 Patch versions don't have breaking changes, so it feels like it's pretty low risk to have slightly different patch versions across individuals' local environments? Or are there other things we should consider? Thank you!

**Comment by jfoo1984** [comment]
That's a good point!  The main considerations I'd have here are absolute consistency across environments, and potential thrash of the `package-lock.json` (I'm not sure if that file is updated when higher patch versions are allowed).

**Pull request merged**
