### PR TITLE
feat(icon): add ChevronLeft2 and ChevronRight2 icons

### PR DESCRIPTION
**Pull request by liaprins**
Add Add ChevronLeft2 and ChevronRight2 icons as size extraSmall and small"

re #530

## Summary

**Icon**
Github issue: #530
 
**Component Name:** ChevronLeft2Small and ChevronRight2Small

**Component Requirements:** 
**Icons can be found on the Google Drive:**
- [x] [ChevronLeft2Small](https://drive.google.com/file/d/12KA19l3nMpaf7bGvyb2qrIv8joq4o_O7/view?usp=drive_link)
- [x] [ChevronRight2Small](https://drive.google.com/file/d/12KWlMVeDfxwhsu6DQa30cgrtbcmL7_ae/view?usp=drive_link)

**Team(s) Requesting:** CZ ID

---

**Related tickets:**

- [ ] #531
- [ ] #532  

## Checklist

- [ ] Default Story in Storybook // liaprins: Icon component has its own test in Storybook
- [ ] LivePreview Story in Storybook // liaprins: Icon component has its own test in Storybook
- [ ] Test Story in Storybook // liaprins: Icon component has its own test in Storybook
- [ ] Tests written // liaprins: Icon component has its own test in Storybook
- [ ] Variables from `defaultTheme.ts` used wherever possible // liaprins: N/A
- [ ] If updating an existing component, depreciate flag has been used where necessary // liaprins: N/A
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

**Here are screenshots of the new icons in their default and hover states:**
chevronLeft2-hover
chevronLeft2-pre-hover
chevronRight2-hover
chevronRight2-pre-hover

### CODE REVIEW

**Review by clarsen-czi — CHANGES_REQUESTED** [review]
Everything looks good with these icon additions, however I noticed that the naming convention for our icons seems to have changed (not sure if it was with this PR or an earlier one, but just noticed it now). We used to name our icons with PascalCase (the first letter in every word, including the first word, is capitalized), whereas now it looks like we're using camelCase (the first letter in every word, excluding the first word, is capitalized). Wondering if you know when this change happened and what prompted it.

**Review by tihuan — APPROVED** [review]
Thanks for adding this, Lia!! 🙏

**Comment by tihuan** [comment]
Ooh great callout, @clarsen-czi! For clarification, I see that the SVG file name is still PascaleCase, just the JS mapping is using camelCase:

Screenshot 2023-07-31 at 2 47 36 PM

So did you mean that the JS mapping used to be PascaleCase too?

Thank you!

**Comment by clarsen-czi** [comment]
Ooh sorry @tihuan , I should have been more specific—I meant the way the names are displayed in Storybook has changed over camelCase. PascalCase is the style we've used in Figma, in our Zeroheight docs, as well as how we've named SVGs, so ultimately I'm just looking for us to pick one and make sure it's consistent everywhere and now it looks like Storybook is the outlier. Ultimately, I think the naming should align to what's best for engineers since you'll be the ones using the names for implementing into product codebases; do you all have a preference? Happy to adjust Zeroheight and Figma on my end to make sure it aligns.

**Review by clarsen-czi — APPROVED** [review]

**Review by masoudmanson — APPROVED** [review]
LGTM :D Thank you for the clean PR @liaprins

**Comment by liaprins** [comment]
Re @clarsen-czi 's comments above about Pascal case vs camelCase, we decided to treat that as a separate issue that won't block these icons being merged in, since it is affecting all the icons, not just these ones. Here's the link to the issue he made: #549

**Pull request merged**
