### PR TITLE
refactor(main): Merging MUIv5 changes from beta branch into the main branch

### PR DESCRIPTION
**Pull request by masoudmanson**
Merging MUIv5 changes from beta branch into the main branch

### CODE REVIEW

**Review by mmmmmmaya — APPROVED** [review]
🚀

**Comment by tihuan** [comment]
YAYY!!! Congratulations everyone!! This is such a huge milestone 🤩 👏 👏 👏 🎉 This team is the best 🚀 ❤️ ✨ !!!

**Review by clarsen-czi — CHANGES_REQUESTED** [review]
Looking great, @masoudmanson  ! There a few small changes which I've added as comments in UI Tests since UI Review wasn't giving me all of the variants to view for some reason.

**Review by clarsen-czi — APPROVED** [review]
LGTM!! Thanks @masoudmanson !!

**Pull request merged**
