### PR TITLE
docs(cell component): change child in default story

### PR DESCRIPTION
**Pull request by bethbertozzi**
## Summary

changed child component to input toggle

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

### CODE REVIEW

**Review by masoudmanson — APPROVED** [review]
Thanks you @bethbertozzi 
LGTM 💯

**Comment by masoudmanson** [comment]
There is only one styling issue, the switch button has a background color that has not been set correctly.

Screen Shot 2022-09-09 at 5 13 39 PM

**Review by clarsen-czi — CHANGES_REQUESTED** [review]
A few changes needed; see comments in Chromatic. Also makes sure Karen takes a look as well.

Thanks @bethbertozzi !

**Review by masoudmanson — APPROVED** [review]
Amazing 🥇 Thanks @bethbertozzi 🤩

**Review by clarsen-czi — APPROVED** [review]
Looks great @bethbertozzi !

**Review by karenliang0 — APPROVED** [review]

**Pull request merged**
