### PR TITLE
fix(button): update SDS ButtonProps to include `component` prop

### PR DESCRIPTION
**Pull request by tihuan**
Somehow MUI ButtonProps does not include `component` prop, so we need to update how we type SDS'
ButtonProps to support `component` prop

Solution was found here: https://stackoverflow.com/a/66123108
UPDATE: Further details regarding `component` prop available on MUI doc [here](https://mui.com/guides/composition/#with-typescript)

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @sds-design

### CODE REVIEW

**Review by bkmartinjr — APPROVED** [review]
LGTM (visual inspection only).  There is an even better discussion on the issue [here](https://mui.com/guides/composition/#with-typescript).

**Comment by tihuan** [comment]
Oh perfect! Thanks so much for linking the doc, @bkmartinjr ! Just added it to the PR description 🚀

**Comment by tihuan** [comment]
@bkmartinjr released! Please upgrade `czifui` and try again 🙏 Thank you!

**Comment by bkmartinjr** [comment]
upgraded and it works.  TY!

**Pull request merged**
