### PR TITLE
refactor(tooltip): rename sdsStyle prop to invertStyle

### PR DESCRIPTION
**Pull request by masoudmanson**
## Summary

**Tooltip**
Github issue: #896 

Connor and I chatted about this and decided to go with a boolean prop called invertStyle with the dark background being the default value (which is "false")

invertStyle: false = dark background Tooltip
invertStyle: true = light background Tooltip
We'll use the same prop on the NavFooter and NavHeader components.

## Checklist

- [ ] Default Story in Storybook
- [ ] LivePreview Story in Storybook
- [ ] Test Story in Storybook
- [ ] Tests written
- [ ] Variables from `defaultTheme.ts` used wherever possible
- [ ] If updating an existing component, depreciate flag has been used where necessary
- [ ] Chromatic build verified by @chanzuckerberg/sds-design

### CODE REVIEW

**Review by clarsen-czi — CHANGES_REQUESTED** [review]
Looks like the new prop works as intended, nicely done! Somehow the screenshot test got messed up if you could look into why. Thanks @masoudmanson !

**Review by tihuan — APPROVED** [review]
LGTM! Non blocking, but given that the new prop is a boolean, I wonder if it's worth prefixing it with `is`? Like `isInvertStyle` to follow the convention of prefixing boolean prop with `is/has/can` etc. 😄 

Thank you!

**Review by tihuan — APPROVED** [review]
Amazing! Thanks so much for addressing this quickly, @masoudmanson ! Really appreciate it ❤️ 🚀 👏 🤩 !!

**Review by clarsen-czi — APPROVED** [review]
LGTM!! Thanks @masoudmanson!

**Pull request merged**
