### PR TITLE
fix(notification): fix forwardRef issue 

### PR DESCRIPTION
**Pull request by masoudmanson**
## Summary

**Notification**
Shortcut ticket: [sh-213346](https://app.shortcut.com/sci-design-system/story/213346/fix-forwardref-issue-with-notification-component)

Resolving this issue (https://czi-sci.slack.com/archives/C032S43KKFV/p1661883090341739)

I couldn't reproduce the same bug but I believe this will solve the problem. 

Reference:
https://github.com/mui/material-ui/issues/31261#issuecomment-1162759589

### CODE REVIEW

**Comment by ehoops-cz** [comment]
Is it possible to push this fix to v6?  I believe @ashin-czi is not on v7 yet.

**Comment by masoudmanson** [comment]
> Is it possible to push this fix to v6? I believe @ashin-czi is not on v7 yet.

Unfortunately, no, because we have fully moved to the new version and could no longer support the old one. 🙁

**Comment by ashin-czi** [comment]
@ehoops-cz  We're currently on v5.5.0, I will try v7 once this is merged!

In the meantime it seems like the Notification component is still rendering!

@masoudmanson But I've noticed some strange visual behavior when trying to use the Notification component with styled-components. It looks like the styled component removes some CSS from the Notification component

<hr>

### Styled:
image
image
```js
import styled from "@emotion/styled";
import { Notification } from "czifui";

export const StyledNotification = styled(Notification)`
  // left empty for example
`;
```
```js
import { StyledNotification, SubmitIssue } from "./style";

export default function Beta(): JSX.Element {
  return (
    <StyledNotification intent="info" autoDismiss={false} dismissDirection="left" onClose={function(){}}>
      This feature is in beta. If you have any suggestions or feeback, please{" "}
      <SubmitIssue
        href="https://docs.google.com/forms/d/e/1FAIpQLSde_zIFZPQD2p0ovaX3Pb7lDOajWJCmOeuX4wQ8Z8Ab5NXUjw/viewform"
        target="_blank"
        rel="noopener"
      >
        submit an issue on our GitHub
      </SubmitIssue>
      .
    </StyledNotification>
  );
}
```

<hr>

### Original:
image
image
```js
import { SubmitIssue } from "./style";
import { Notification } from "czifui";

export default function Beta(): JSX.Element {
  return (
    <Notification intent="info" autoDismiss={false} dismissDirection="left" onClose={function(){}}>
      This feature is in beta. If you have any suggestions or feeback, please{" "}
      <SubmitIssue
        href="https://docs.google.com/forms/d/e/1FAIpQLSde_zIFZPQD2p0ovaX3Pb7lDOajWJCmOeuX4wQ8Z8Ab5NXUjw/viewform"
        target="_blank"
        rel="noopener"
      >
        submit an issue on our GitHub
      </SubmitIssue>
      .
    </Notification>
  );
}

```

<hr>

You can see that in the styled component it's missing the left border and the shadow. From looking at the final HTML, the element is missing the `elevated` class, which have these properties:
image

Here is the code for the styled-component:
```javascript
import styled from "@emotion/styled";
import { Notification } from "czifui";

export const StyledNotification = styled(Notification)`
  // left empty for example
`;
```

I'm unsure if this is a bug with the styled-components library, or if this is something related to the issue in this PR. 

Would be glad to hear some thoughts on this!

Thanks!

**Comment by masoudmanson** [comment]
> ```js
> import { Notification } from "czifui";
> 
> export const StyledNotification = styled(Notification)`
>   // left empty for example
> `;
> ```

Thank you for spotting this bug :D It's fixed in this PR now. 

A workaround for the old version could be setting a className of `elevated` to the StyledNotification component. 

```javascript
const StyledNotification = styled(Notification)`
  // left empty for example
`;

<StyledNotification
  intent="warning"
  autoDismiss={false}
  dismissDirection="left"
  onClose={function () {}}
  className="elevated"
>
  This feature is in beta. If you have any suggestions or feeback,
  please.
</StyledNotification>
```

Here is a working demo:
https://codesandbox.io/s/sds-notification-joh2ve

**Comment by ashin-czi** [comment]
> A workaround for the old version could be setting a className of `elevated` to the StyledNotification component.

This worked for me, thank you so much! Was able to style the whole notification now :]
image

**Review by mmmmmmaya — APPROVED** [review]

**Pull request merged**
