### PR TITLE
fix: implement add use client to all sds components

### PR DESCRIPTION
**Pull request by masoudmanson**
## Summary

**All SDS Components**
Github issue: #814 

We nee to add "use client"; in all SDS component files, so projects don’t have to do that manually themselves like here:
https://github.com/czbiohub-sf/CZBSF-Metadata-Tracker-refactor/pull/82#discussion_r1684929746

### CODE REVIEW

**Review by tihuan — COMMENTED** [review]
Thanks so much for adding this, @masoudmanson !

Sorry for just realizing this, but it seems like in this thread, we might be able to mark the exported modules with `"use client"` automagically by doing this in rollup config!

https://github.com/rollup/rollup/issues/4699#issuecomment-2273497055

And if we ever need to selectively apply "use client" in just some files, there's a plugin for that now too 😄 

https://github.com/rollup/rollup/issues/4699#issuecomment-2275883910

**Comment by masoudmanson** [comment]
> Thanks so much for adding this, @masoudmanson !
> 
> Sorry for just realizing this, but it seems like in this thread, we might be able to mark the exported modules with `"use client"` automagically by doing this in rollup config!
> 
> [rollup/rollup#4699 (comment)](https://github.com/rollup/rollup/issues/4699#issuecomment-2273497055)
> 
> And if we ever need to selectively apply "use client" in just some files, there's a plugin for that now too 😄
> 
> [rollup/rollup#4699 (comment)](https://github.com/rollup/rollup/issues/4699#issuecomment-2275883910)

OMG nooo 😯😱🤣
This is so embarrassing! I should have checked it myself! I thought we actually needed to add the directive on top of every single component 😬
Thank you for digging that up, it really makes a huge difference 🥳🎉🤩
I'll leave this PR here and create a new one with the rollup changes.

**Comment by tihuan** [comment]
> > Thanks so much for adding this, @masoudmanson !
> > Sorry for just realizing this, but it seems like in this thread, we might be able to mark the exported modules with `"use client"` automagically by doing this in rollup config!
> > [rollup/rollup#4699 (comment)](https://github.com/rollup/rollup/issues/4699#issuecomment-2273497055)
> > And if we ever need to selectively apply "use client" in just some files, there's a plugin for that now too 😄
> > [rollup/rollup#4699 (comment)](https://github.com/rollup/rollup/issues/4699#issuecomment-2275883910)
> 
> OMG nooo 😯😱🤣 This is so embarrassing! I should have checked it myself! I thought we actually needed to add the directive on top of every single component 😬 Thank you for digging that up, it really makes a huge difference 🥳🎉🤩 I'll leave this PR here and create a new one with the rollup changes.

Ahaha I thought we had to manually add it ourselves too, so I probably misled you 😆 🤦 !! Thanks so much for creating a new PR!! 😂

**Comment by masoudmanson** [comment]
H

**Pull request closed without merging**
