### PR TITLE
fix(textfield): change inputMarginDense to inputSizeSmall

### PR DESCRIPTION
**Pull request by codemonkey800**

### CODE REVIEW

**Review by tihuan — APPROVED** [review]
LGTM 👏 !!

**Comment by tihuan** [comment]
Looks like we just need to update the snapshots 🙆‍♂️ ! 

Sorry can't do it for you since it's on your fork 😭

**Comment by codemonkey800** [comment]
lol updated snapshots. this happens all the time for PRs on the napari hub 😆

**Comment by tihuan** [comment]
ahaha same 😆 !

**Pull request merged**
